import { useEffect } from "react";
import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import { AuthProvider } from "@/app/contexts/AuthContext";

const kanitFont = Kanit({
  variable: "--font-kanit",
  subsets: ["latin", "thai"],
  weight: ["300", "400", "600"],
});

export const metadata = {
  title: "แพลตฟอร์มจองสนามกีฬาออนไลน์",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({ children }) {
  const [allLoading, setAllLoading] = useState(true);
  useEffect(() => {
    if (!isLoading && !dataLoading) {
      setAllLoading(false);
    } else {
      setAllLoading(true);
    }
  }, [isLoading, dataLoading]);
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${kanitFont.variable} antialiased`}>
          <div className="navbar">
            <Navbar></Navbar>
          </div>
          <div className="body">{children}</div>
          <footer>
            <Footer></Footer>
          </footer>
        </body>
      </AuthProvider>
    </html>
  );
}
