"use client"; // Add this line to indicate that this is a client component

import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import { useRouter } from "next/navigation";

const kanitFont = Kanit({
  variable: "--font-kanit",
  subsets: ["latin", "thai"],
  weight: ["300", "400", "600"],
});

export const metadata = {
  title: "แพลตฟอร์มจองสนามกีฬาออนไลน์",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function RootLayout({ children }) {
  const router = useRouter();
  const isConfirmResetPassword = router.pathname === "/confirmResetPassword";

  return (
    <html lang="en">
      <body className={`${kanitFont.variable} antialiased`}>
        <div className="navbar">
          {!isConfirmResetPassword && <Navbar />}
        </div>
        <div className="body">{children}</div>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
